Create an Origami Component following v2 of the specification
Financial-Times/create-origami-component pull request #238
Opened 2021-02-17 11:25 UTC by notlee

Draft Specification: https://github.com/Financial-Times/origami-website/pull/273

Closes: https://github.com/Financial-Times/create-origami-component/issues/220

Changes were reviewed here: https://github.com/Financial-Times/create-origami-component/pull/235

2021-02-17 11:28 UTC, notlee commented
Percy shows the icons are missing because the image service hasn't released yet

2021-04-08 10:56 UTC, JakeChampion commented on templates/npmignore.js
> +.stylelintrc.js
```suggestion
.eslintrc.cjs
.github/
.gitignore
.remarkrc.cjs
.stylelintrc.cjs
```

2021-04-08 10:56 UTC, JakeChampion commented on templates/origami-manifest.js
> +	"origamiVersion": 2,
```suggestion
	"origamiVersion": "2.0",
```

2021-04-08 10:58 UTC, JakeChampion commented on templates/package-json.js
> +		});
Let's remove the typescript parts for now, we haven't added it to any of the spec v2 components we are currently working on
```suggestion
		Object.assign(packageJson, {
			"browser": "./main.js",
		});
```

2021-04-08 10:58 UTC, JakeChampion commented on templates/package-json.js
> +		});
```suggestion
```

2021-04-08 10:58 UTC, JakeChampion commented on templates/package-json.js
> +			"typescript": "^4.0.5"
```suggestion
			"eslint-config-origami-component": "^2.1.0"
```

2021-04-28 17:00 UTC, notlee commented
This released as `v0.3.2` since I used the patch release label but the existing beta tag does not reference this branch.

2021-07-05 11:09 UTC, JakeChampion requested changes, later dismissed

2021-07-05 11:09 UTC, JakeChampion commented on package.json
> +    "origami-build-tools": "prerelease",
```suggestion
    "origami-build-tools": "^11",
```

2021-07-05 11:09 UTC, JakeChampion commented on templates/package-json.js
> +			"remark-preset-lint-origami-component": "^2.0.0-beta.1"
```suggestion
			"remark-preset-lint-origami-component": "^2.0.0"
```

2021-07-05 11:09 UTC, JakeChampion commented on templates/package-json.js
> +			"@financial-times/o-brand": "^4.0.0-beta.0"
```suggestion
			"@financial-times/o-brand": "^4.0.0"
```

2021-07-05 11:09 UTC, JakeChampion commented on templates/workflows/test-origami-component.yml
> +    - run: npm install -g origami-build-tools@prerelease
```suggestion
    - run: npm install -g origami-build-tools@^11
```

2021-07-05 11:22 UTC, JakeChampion commented on templates/workflows/test-origami-component.yml
> +    - run: npm install -g origami-build-tools@prerelease
fixed in [`7733640` (#238)](https://github.com/Financial-Times/create-origami-component/pull/238/commits/7733640bb2ff9c761fd2babfa3fe5e8260d1db84)

2021-07-05 11:22 UTC, JakeChampion commented on package.json
> +    "origami-build-tools": "prerelease",
fixed in [`7733640` (#238)](https://github.com/Financial-Times/create-origami-component/pull/238/commits/7733640bb2ff9c761fd2babfa3fe5e8260d1db84)

2021-07-05 11:22 UTC, JakeChampion commented on templates/package-json.js
> +			"@financial-times/o-brand": "^4.0.0-beta.0"
fixed in [`1b0e344` (#238)](https://github.com/Financial-Times/create-origami-component/pull/238/commits/1b0e3449b950710fc2defeaab53eac4faeb36ea9)

2021-07-05 11:22 UTC, JakeChampion commented on templates/package-json.js
> +			"remark-preset-lint-origami-component": "^2.0.0-beta.1"
fixed in [`1b0e344` (#238)](https://github.com/Financial-Times/create-origami-component/pull/238/commits/1b0e3449b950710fc2defeaab53eac4faeb36ea9)

2021-07-05 11:29 UTC, chee approved these changes

2021-07-05 12:34 UTC, merged

2021-07-05 12:35 UTC, origamiserviceuser commented
:tada: This PR is included in version v1.0.0 :tada: